config/routes.rb
Rails.application.routes.draw do
#   get 'pages/about'
#   get 'pages/contact'
#   get 'pages/home'
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#   get "/pages/:about" => "pages#show"

root 'posts#index'





resources :posts


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end

  def new
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index

    @posts = Post.all

    end

    def new

    end

    def show
        @post = Post.find(params[:id])
    end

    def create
        # render plain: params[:post].inspect
        @post = Post.new(post_params)

        @post.save
        redirect_to @post
    end

    private def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Firstproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link tag <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> <%=@title %></h1>
<p> <%=@content %></p>

app/views/posts/index.html.erb
<h1>Index</h1>
<% @posts.each do |post| %>
    <h3><%=post.title %></h3>
    <p> <%=post.body %></p>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>

<%= form_for :post, url: posts_path do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :body %>:
  <%= f.text_field :body %><br />

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p> <%= @post.body %></p>